"""FROZEN pre-registration for the forward paper test of the 92/8 core+satellite
allocation portfolio (core: 60/40 SPY/IEF; satellite: the pre-registered C1 BTC
4-week trend rule), on the Alpaca paper instance ($100k). The IBKR instance
keeps running the old 11-strategy system unchanged, as the control.

Written and fingerprinted BEFORE the allocator job is deployed or any live cycle
has run. Historical sanity numbers referenced below come from
``scripts/allocation_portfolio_backtest.py`` / ``docs/allocation_portfolio_backtest_2026_09.json``,
which is NOT a new edge claim -- it reuses the already-fingerprinted C1 rule from
``scripts/alt_premia_preregistered_bars.py`` (``docs/edge_search_verdict_2026_09.md``).
Do not edit this file once the allocator has started trading: a changed
fingerprint means the run no longer tests the frozen design. A genuinely new
design needs a new file and a new ledger entry in
``docs/allocation_forward_test_trial_history.json``.

Question this forward test can actually answer: is the allocator implemented
correctly and does it behave safely under real fills, real timing and real
costs? It CANNOT, on any realistic monitoring horizon, tell us whether the BTC
sleeve has genuine edge -- see POWER_CALCULATION. That is disclosed up front,
not discovered after the fact.
"""

from __future__ import annotations

import hashlib
import json

PREREGISTERED_AT = "2026-09-30T12:00:00Z"

# ---------------------------------------------------------------------------
# Deployment identity (frozen once known)
# ---------------------------------------------------------------------------
# The forward test's start date cannot be known before the allocator job is
# actually deployed and takes its first live cycle. Per the "never edit a live
# checkout" / "no config or live-service changes in this session" rules, that
# deployment is a separate, later action by the owner. When it happens, the
# resolved start date is recorded as a NEW entry in
# docs/allocation_forward_test_trial_history.json (fingerprint + resolved
# start_date + broker account id), NOT by editing START_DATE below. This keeps
# the bars themselves frozen regardless of when deployment actually occurs.
START_DATE = None  # placeholder: "first live allocation cycle" timestamp, resolved at deploy
MIN_DURATION_MONTHS = 6
MIN_DURATION_RATIONALE = (
    "6 months covers >=6 core monthly rebalances and >=25 weekly BTC sleeve "
    "reviews (enough to see multiple signal flips given C1's historical flip "
    "rate). The drift band fires rarely -- 22 times in 2931 trading days "
    "(2015-2026), about once every 6 months on average -- so a 6-month window "
    "should see roughly zero or one band-triggered trade, not several; if "
    "verifying the drift-band mechanism specifically matters, extend "
    "monitoring until at least one such trade has been observed and audited. "
    "6 months is NOT long enough, and is not intended to be long enough, to "
    "detect the BTC sleeve's backtested edge -- see POWER_CALCULATION. "
    "Implementation/risk bars (I1-I5) are evaluated on a rolling basis from "
    "month 1; they do not wait for month 6."
)

# ---------------------------------------------------------------------------
# The exact portfolio under test (must match the live allocator config exactly;
# any parameter drift between this block and the deployed config is itself an
# I5 violation -- see BARS_IMPLEMENTATION)
# ---------------------------------------------------------------------------
PORTFOLIO = {
    "instance": "Alpaca paper, $100k, one account",
    "control_instance": "IBKR paper (config/live.yaml): unchanged 11-strategy blended system",
    "core": {
        "weight_of_nav": 0.92,
        "targets": {"SPY": 0.6, "IEF": 0.4},
        "rebalance": "close of the first US trading day of each calendar month",
        "drift_band_abs": 0.02,
        "drift_band_check": "daily, in addition to the monthly clock",
    },
    "satellite": {
        "weight_of_nav": 0.08,
        "rule": "C1_btc_trend, unmodified, from alt_premia_preregistered_bars.CANDIDATES['C1_btc_trend']",
        "signal": "long BTC iff 28-day return > 0 at the Sunday UTC close",
        "sizing": "min(1, 0.40 / (63-day realised vol x sqrt(365))) of the sleeve's own capital",
        "band_abs": 0.10,
        "lag_days": 1,
        "cost_bps_per_side": 25.0,
    },
    "capital_treatment": "sleeved (independent per-sleeve capital/P&L; matches capital_allocation_mode: sleeved "
                          "already live on Alpaca). The 92/8 split is NOT automatically restored between "
                          "sleeves; docs/allocation_portfolio_backtest_2026_09.json shows this lets the "
                          "satellite's actual NAV share drift far from 8% over multi-year horizons "
                          "(satellite_actual_share). BAR_SLEEVE_DRIFT below monitors this in the forward test.",
    "reused_prereg_fingerprint_backtest": "see docs/allocation_portfolio_backtest_2026_09.json['reused_prereg_fingerprint']",
}

# ---------------------------------------------------------------------------
# What is measured
# ---------------------------------------------------------------------------
MEASURES = {
    "live_nav": "daily NAV from the Alpaca broker API (same source as the existing live dashboard), "
                "end-of-day, after that day's fills settle",
    "simulated_nav": "a parallel NAV computed OFFLINE from the same rule set (PORTFOLIO above) applied "
                      "deterministically to realised market closes (same data source/adjustment convention as "
                      "scripts/allocation_portfolio_backtest.py), starting from the live account's actual "
                      "starting NAV on START_DATE -- this is the implementation-correctness reference, not a "
                      "second edge claim",
    "tracking_error": "daily (live_nav return - simulated_nav return); this checks the IMPLEMENTATION "
                       "(fills, timing, real costs, rounding, partial fills), not an edge",
    "fills_vs_close": "each order's average fill price vs that instrument's close on the trading day the "
                       "target was set, in bps",
    "turnover_vs_expected": "trade count and $ traded per month vs the count/$ predicted by replaying the "
                             "rule set on realised closes (same simulation as simulated_nav)",
    "unmanaged_drift": "every order in the Alpaca account must map to a logged allocator decision "
                        "(monthly core rebalance, daily drift-band trigger, or weekly BTC sleeve review); "
                        "any order without one is a hard fail, investigated same-day",
    "control_series": "IBKR instance's own live NAV, unchanged 11-strategy system, same calendar",
}

# ---------------------------------------------------------------------------
# Bars: implementation correctness (this IS gate-able on a 6-month horizon)
# ---------------------------------------------------------------------------
BARS_IMPLEMENTATION = [
    {"id": "I1_tracking_error",
     "rule": "rolling 63-trading-day tracking error (live NAV return - simulated NAV return) has "
             "|mean| <= 5 bps/day and stdev <= 15 bps/day, after excluding days with a broker-confirmed "
             "corporate action or outage (logged separately, not silently dropped)"},
    {"id": "I2_cumulative_drift",
     "rule": "|live NAV / simulated NAV - 1| <= 2% at every month-end (catches slow-building implementation "
             "bugs that a daily average would hide)"},
    {"id": "I3_fills",
     "rule": "median |fill price / that day's close - 1| <= 15 bps for SPY/IEF and <= 60 bps for BTC/USD "
             "(crypto spread is wider); no single fill > 100 bps / 300 bps respectively without a logged "
             "reason (halt, gap, thin book)"},
    {"id": "I4_turnover",
     "rule": "monthly trade count within +/-1 of the simulation's predicted count for the core, and every "
             "drift-band / BTC-sleeve trade traceable to a logged trigger with the breaching weight recorded"},
    {"id": "I5_no_unmanaged_drift",
     "rule": "100% of orders map to a logged allocator decision; the live PORTFOLIO parameters (weights, "
             "bands, lag, costs) match this file's frozen block bit-for-bit at every audit"},
    {"id": "BAR_SLEEVE_DRIFT",
     "rule": "report (not gated): the satellite's actual share of NAV each month-end, flagged if it moves "
             "outside [0.04, 0.16] (2x target either way) -- the historical backtest shows this WILL happen "
             "over long enough horizons under the sleeved (no cross-rebalance) convention; a flag here is "
             "informational for the owner's periodic-rebalance decision, not an implementation failure"},
]
IMPLEMENTATION_ACTION = {
    "all_pass": "implementation verified; continue monitoring, no code/config change needed",
    "any_fail": "halt new allocator-driven orders on the Alpaca instance (FIRM_ALLOW_TRADING style gate or "
                "equivalent), diagnose against the simulation, fix, re-verify I1-I5 on a fresh window before "
                "resuming -- this is a live-trading correctness bug, handled with the usual incident priority",
}

# ---------------------------------------------------------------------------
# Bars: satellite forward performance (reported, NOT gated -- see POWER_CALCULATION)
# ---------------------------------------------------------------------------
BARS_SATELLITE_FORWARD = [
    {"id": "F1_sign",
     "rule": "reported only: sign and magnitude of (Sharpe of the live satellite sleeve's realised returns) "
             "minus (Sharpe of BTC held at C1's matched average exposure over the same forward window, "
             "priced from the same closes) -- the same comparison C1 was evaluated against historically"},
    {"id": "F2_drawdown_containment",
     "rule": "gated: the satellite sleeve's own drawdown (as a fraction of the SATELLITE's capital, not "
             "total NAV) must never exceed 60% without a same-day owner alert (V1_short_vol_timed-style tail "
             "bar); this is a risk bar, not an edge bar -- the backtest's satellite-alone max drawdown was 49%"},
    {"id": "F3_no_worse_than_flat_btc",
     "rule": "reported only: is the live sleeve's cumulative return worse than simply holding cash the whole "
             "forward window (a sanity floor, not a Sharpe comparison)"},
]
SATELLITE_FORWARD_NOTE = (
    "F1 and F3 are diagnostic, not pass/fail on the pre-registered design: POWER_CALCULATION shows this "
    "forward test cannot reach 80% power to detect the backtested +0.28 Sharpe gap on any realistic "
    "monitoring horizon. Do not read a positive or negative F1 over 6-24 months as evidence of edge either "
    "way; the sample is too small to distinguish either from noise at this effect size."
)

# ---------------------------------------------------------------------------
# Power calculation: how long to detect the backtested Sharpe gap of +0.28
# (C1_btc_trend vs BTC_BH_MATCHED, the same pair and formula used for the MDE
# table in run_alt_premia_evaluation.cmd_power / docs/alt_premia_power_analysis_2026_09.json,
# but solved for the sample size n needed to detect a KNOWN gap, rather than the
# gap detectable at a KNOWN n).
# ---------------------------------------------------------------------------
POWER_CALCULATION = {
    "method": "Jobson-Korkie/Memmel paired-Sharpe-difference variance, solved for n given a target gap; "
              "same formula family as run_alt_premia_evaluation.cmd_power",
    "target_gap_annualized_sharpe": 0.28,
    "target_gap_source": "the C1_btc_trend vs BTC_BH_MATCHED point estimate in "
                          "docs/edge_search_verdict_2026_09.md Sec.3 (Sharpe 1.35 vs 1.07)",
    "alpha_one_sided": 0.05,
    "power_target": 0.80,
    "z_alpha": 1.6449,
    "z_beta": 0.8416,
    "inputs_from_backtest": {
        "source": "docs/allocation_portfolio_backtest_2026_09.json (window 2015-02-01 to 2026-09-28, n=2931 days)",
        "sharpe_btc_bh_matched_full_history": 1.074,
        "sharpe_c1_full_history": 1.354,
        "empirical_daily_excess_return_correlation_c1_vs_matched": 0.726,
    },
    "formula": "n_days = (z_a+z_b)^2 * [2(1-rho) + 0.5(sb_d^2+sc_d^2-2 sb_d sc_d rho^2)] / (g/ANN)^2, "
               "sb_d/sc_d = daily (non-annualised) Sharpes, g = target annualised gap, ANN = sqrt(252)",
    "results": {
        "at_empirical_rho_0.726": {"n_trading_days": 10959, "years": 43.5, "months": 522},
        "at_conservative_rho_0.0": {"n_trading_days": 39863, "years": 158.2, "months": 1898,
                                     "note": "rho=0 ignores that a trend-following overlay and its own "
                                             "underlying asset share most of their variance; treat as an "
                                             "upper bound, not the expected case"},
    },
    "conclusion": "Detecting the backtested Sharpe gap forward would take on the order of 40+ years even "
                  "under the historically-observed correlation, and up to ~160 years under a conservative "
                  "independence assumption. No realistic paper-test duration (6 months, 1 year, even "
                  "several years) can distinguish this edge from noise. The forward test's value is "
                  "therefore entirely in BARS_IMPLEMENTATION and BARS_SATELLITE_FORWARD's risk bar (F2), "
                  "not in proving or disproving the +0.28 Sharpe gap.",
}

# ---------------------------------------------------------------------------
# Control comparison vs the IBKR instance
# ---------------------------------------------------------------------------
CONTROL_COMPARISON = {
    "purpose": "operational/qualitative control, not a powered hypothesis test -- the two instances differ "
               "in strategy, broker, capital mode and (per docs/edge_search_verdict_2026_09.md) the IBKR "
               "instance's own live config already measured Sharpe-above-T-bills 0.14 historically. A "
               "forward comparison over 6-24 months has the same power problem as POWER_CALCULATION and "
               "then some (both series are noisy, uncorrelated strategies).",
    "what_is_reported": [
        "side-by-side monthly NAV, CAGR, realised vol, max drawdown, Sharpe-above-T-bills for both instances",
        "whether the Alpaca (60/40+BTC) instance's realised drawdown stayed inside the calibrated kill-switch "
        "band (see docs/allocation_portfolio_backtest_2026_09.json's drawdown_distribution) while the IBKR "
        "control continues under its existing 8% kill_switch_drawdown",
        "any kill-switch trips or news-guard holds on either instance, and why",
    ],
    "not_claimed": "neither instance beating the other over the forward window is evidence of which "
                   "strategy is better; both are far below the sample size such a claim would need",
}

FINDINGS_ACTIONS = {
    "stop_satellite": "any BARS_IMPLEMENTATION fail that cannot be fixed within one incident cycle; OR "
                       "F2 tail bar breach (satellite drawdown > 60% of sleeve capital) without an owner "
                       "override; OR a live parameter drifting from the frozen PORTFOLIO block (I5)",
    "scale_satellite": "not supported by this design at any point -- POWER_CALCULATION means no forward "
                        "result from this test should be used to justify increasing the satellite's weight "
                        "above 8%; a scale-up decision would need a new pre-registration with its own power "
                        "budget (i.e. a materially longer commitment or a larger claimed effect size)",
    "keep_running_unchanged": "all of BARS_IMPLEMENTATION pass and F2 is not breached -- this is the "
                               "expected steady state and is itself the useful result (a working, safe "
                               "60/40+BTC allocator), independent of F1's sign",
}


def bars_fingerprint() -> str:
    payload = json.dumps(
        {
            "PREREGISTERED_AT": PREREGISTERED_AT, "MIN_DURATION_MONTHS": MIN_DURATION_MONTHS,
            "MIN_DURATION_RATIONALE": MIN_DURATION_RATIONALE,
            "PORTFOLIO": PORTFOLIO, "MEASURES": MEASURES,
            "BARS_IMPLEMENTATION": BARS_IMPLEMENTATION, "IMPLEMENTATION_ACTION": IMPLEMENTATION_ACTION,
            "BARS_SATELLITE_FORWARD": BARS_SATELLITE_FORWARD,
            "POWER_CALCULATION": POWER_CALCULATION, "CONTROL_COMPARISON": CONTROL_COMPARISON,
            "FINDINGS_ACTIONS": FINDINGS_ACTIONS,
        },
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode()).hexdigest()


if __name__ == "__main__":
    print(bars_fingerprint())
